environment:

  - name : "MFS-debug"
    stream_governance_package : "ESSENTIALS"
    network:
      # - name: "PSC-KFK-STAA"
      #   connection_types: "PRIVATELINK"
      #   cloud_provider: "GCP"
      #   region: "europe-west1"       
      #   zones: ["europe-west1-b", "europe-west1-c", "europe-west1-d"]
      #   network_config :  
      #     - ingress_connection_name: "ingress_connnection"  
      #       project_id: "irn-72775-kfk-sta-450"

      # - name: "PSC-KFK-DEBUG"
      #   connection_types: "PRIVATELINK"
      #   cloud_provider: "GCP"
      #   region: "europe-west1"       
      #   zones: ["europe-west1-b", "europe-west1-c", "europe-west1-d"]
      #   network_config :  
      #     - ingress_connection_name: "PSC-IRN-72775-KFK-DEV-CNX"  
      #       project_id: "irn-72775-kfk-dev-39"

      #     - ingress_connection_name: "CNX-host-project-euwest1-1"  
      #       project_id: "host-project-euwest1-1"

      #     - ingress_connection_name: "PSC-irn-73453-ope-b1"  
      #       project_id: "irn-73453-ope-b1"

    # cluster :
    #   name : "mfs-cluster-debug"
    #   type : "dedicated"
    #   cloud_provider : "GCP"
    #   region : "europe-west1"
    #   availability_zone : "SINGLE_ZONE"
    #   cku : 1
      # network : "PSC-KFK-DEBUG"        
    cluster :
      name : "cluster-debug"
      type : "standard"
      cloud_provider : "GCP"
      region : "europe-west1"
      availability_zone : "SINGLE_ZONE"
      cku : 1
      # network : ""
      
    ksql :
       csu : 1  

    flink:
      max_cfu: 5





