environment:

  - name : "MFS-debug"
    stream_governance_package : "ESSENTIALS"
    network: 
    cluster :
      name : "cluster-debug"
      type : "standard"
      cloud_provider : "GCP"
      region : "europe-west1"
      availability_zone : "SINGLE_ZONE"
      cku : 1
    ksql :
       csu : 1  
    flink:
      max_cfu: 5






