environment:

  - name : "MFS-dev"
    stream_governance_package : "ESSENTIALS"
    network:
      - name: "PSC-KFK-DEV"
        connection_types: "PRIVATELINK"
        cloud_provider: "GCP"
        region: "europe-west1"       
        zones: ["europe-west1-b", "europe-west1-c", "europe-west1-d"]
        network_config :  
        
          - ingress_connection_name: "PSC-IRN-72775-KFK-DEV-CNX"  
            project_id: "irn-72775-kfk-dev-39"

          - ingress_connection_name: "CNX-host-project-euwest1-1"  
            project_id: "host-project-euwest1-1"

          - ingress_connection_name: "PSC-irn-73453-ope-b1"  
            project_id: "irn-73453-ope-b1"

          - ingress_connection_name: "PSC-irn-79267-kio-dev-b8"  
            project_id: "irn-79267-kio-dev-b8"

          - ingress_connection_name: "PSC-irn-73453-dev-0f"  
            project_id: "irn-73453-dev-0f"

          - ingress_connection_name: "PSC-irn-80416-xhb-dev-15"  
            project_id: "irn-80416-xhb-dev-15"

          - ingress_connection_name: "PSC-irn-80705-xdp-dev-8f"  
            project_id: "irn-80705-xdp-dev-8f"       

          - ingress_connection_name: "PSC-irn-80705-xhb-dev-a1"  
            project_id: "irn-80705-xhb-dev-a1"

    cluster :
      name : "mfs-cluster-dev"
      type : "dedicated"
      cloud_provider : "GCP"
      region : "europe-west1"
      availability_zone : "SINGLE_ZONE"
      cku : 1
      network : "PSC-KFK-DEV"

    ksql :
       csu : 1  

    flink:
      max_cfu: 5


    # cluster :
    #   name : "cluster-dev"
    #   type : "basic"
    #   cloud_provider : "GCP"
    #   region : "europe-west1"
    #   availability_zone : "SINGLE_ZONE"


      # - name: "my_network2"
      #   connection_types: "PRIVATELINK"
      #   cloud_provider: "GCP"
      #   region: "europe-west1"       
      #   zones: ["europe-west1-b", "europe-west1-c", "europe-west1-d"]
      #   network_config :  
      #     - ingress_connection_name: "PSC1"  
      #       project_id: "host-project-euwest1-1"

      #     - ingress_connection_name: "PSC2"  
      #       project_id: "irn-73704-xch-int-dev-ad"

      
  # - name : "MFS-dev"
  #   stream_governance_package : "ESSENTIALS"
  #   cluster :
  #     name : "cluster-dev"
  #     type : "dedicated"
  #     cloud_provider : "GCP"
  #     region : "europe-west1"
  #     availability_zone : "SINGLE_ZONE"
  #     cku : 1




